package helpers;
import data.*;

import java.io.IOException;
import java.sql.*;
import java.util.LinkedList;
import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReadWriteLock;
import java.util.concurrent.locks.ReentrantReadWriteLock;

/**
 * @author Sabitov Danil
 * @version 1.0
 * Class describing commands that manage USERS table in database
 */
public class UserManager {
    private Connection c;
    private Statement stmt;
    private ReadWriteLock readWriteLock = new ReentrantReadWriteLock();
    private Lock readLock = readWriteLock.readLock();
    private Lock writeLock = readWriteLock.writeLock();


    /*
           public void createTable(){
            try {
                Class.forName("org.postgresql.Driver");
                c = DriverManager
                        .getConnection("jdbc:postgresql://localhost:9800/studs","s313318", "mes758");
                System.out.println("Opened database successfully");

                stmt = c.createStatement();
                String sql = "CREATE TABLE organizations " +
                        "( id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 4 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ," +
                        " name text COLLATE pg_catalog.\"default\" NOT NULL, " +
                        "  annualturnover integer NOT NULL," +
                        "creationdate timestamp without time zone NOT NULL," +
                        " fullname text COLLATE pg_catalog.\"default\"," +
                        " organizationtype text COLLATE pg_catalog.\"default\" NOT NULL," +
                        "street text COLLATE pg_catalog.\"default\" NOT NULL," +
                        "townx integer," +
                        "  towny real," +
                        "coordx real," +
                        "coordy real," +
                        " townname text COLLATE pg_catalog.\"default\"," +
                        "userid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 )," +
                        "CONSTRAINT organizations_pkey PRIMARY KEY (id))";
                stmt.executeUpdate(sql);
                stmt.close();
                c.close();
            } catch ( Exception e ) {
                System.err.println( e.getClass().getName()+": "+ e.getMessage() );
                System.exit(0);
            }
            System.out.println("Table created successfully");
        }


     */



    public String addingUser(String login, String password){
        String result = "";
        try {
        Class.forName("org.postgresql.Driver");
            c = DriverManager.getConnection("jdbc:postgresql://localhost:9800/studs","s313318", "mes758");
            //c = DriverManager.getConnection("jdbc:postgresql://pg:5432/studs","s313318", "mes758");
        c.setAutoCommit(false);
        System.out.println("-- Opened database successfully");
        String sql = "";
        System.out.println("Login = " + login + " " + "Password = " + password);
        stmt = c.createStatement();
        sql = "INSERT INTO USERS (LOGIN, PASSWORD) VALUES ('"+ login +"', '"+ password +"');";
        //sql = "SELECT L.*, S.Description FROM Log as L LEFT JOIN Stations as S ON L.id_station = S.id_station WHERE S.id_station = 5";
        System.out.println(sql);

        writeLock.lock();
        //readLock.lock();
        stmt.executeUpdate(sql);
        //readLock.unlock();
        writeLock.unlock();

        ResultSet rs = stmt.executeQuery( "SELECT * FROM USERS;" );
        Integer id = null;
            while ( rs.next() ) {
                id = rs.getInt("id");
            }
        stmt.close();
        c.commit();
        System.out.println("--New user was added successfully!" + id);
        result +=  "New user was added successfully!" + id;
    }catch (ClassNotFoundException | SQLException |NullPointerException e) {
        System.out.println("User was not added! "  + e.getMessage());
    }
        return result;
}

public String checkingID(String command, Integer id, String userId) {
    String result = "";
    try {
    Class.forName("org.postgresql.Driver");
        c = DriverManager.getConnection("jdbc:postgresql://localhost:9800/studs","s313318", "mes758");
        //c = DriverManager.getConnection("jdbc:postgresql://pg:5432/studs","s313318", "mes758");
    c.setAutoCommit(false);
    stmt = c.createStatement();

        System.out.println("-- Opened database successfully");
        readLock.lock();
        //writeLock.lock();
        ResultSet rs = stmt.executeQuery("SELECT USERID FROM ORGANIZATIONS WHERE ID = " + id + " ;");
        //writeLock.unlock();
        readLock.unlock();
        result = "$CheckId$=" + command + "=" + id + "=";
        if (rs.next()) {
            String userFromData = rs.getString(1);
            if (!userFromData.equals(userId)){
                result += "NoAccess";
            }else {
                result += "true";
            }
        } else {
            result += "false";
        }
        rs.close();
        stmt.close();
        c.commit();
    }catch (ClassNotFoundException | SQLException e){
        System.out.println("Error with checking id!");
    }
    return result;
}


    public String testingUser(String login, String password){
        String result = "";
        try {
            Class.forName("org.postgresql.Driver");
            c = DriverManager.getConnection("jdbc:postgresql://localhost:9800/studs","s313318", "mes758");
            //c = DriverManager.getConnection("jdbc:postgresql://pg:5432/studs","s313318", "mes758");
            c.setAutoCommit(false);
            System.out.println("-- Opened database successfully");
            String sql = "";
            System.out.println("Login = " + login + " " + "Password = " + password);
            stmt = c.createStatement();
            sql = "SELECT * FROM USERS WHERE LOGIN = '"+ login + "' AND PASSWORD = '"+ password +"';";
            //sql = "SELECT L.*, S.Description FROM Log as L LEFT JOIN Stations as S ON L.id_station = S.id_station WHERE S.id_station = 5";
           // System.out.println(sql);

            writeLock.lock();
            ResultSet rs = stmt.executeQuery( sql );
            writeLock.unlock();
            Integer id = null;
            // int count = rs.next();
            if (rs.next()){
                id = rs.getInt("id");
                result = "Welcome registered user!" + id;
            }
            else {
                result = "Users with this login/password don't exist";
            }
            stmt.close();
            c.commit();
        }catch (ClassNotFoundException | SQLException |NullPointerException e) {
            System.out.println("Error with testing login and password! "  + e.getMessage());
        }
        return result;
    }

}
